#!/usr/bin/env bash
#This script displays to infinity and beyond indefinitely
#in between each iteration add a sleep 2
counter=0
while [$counter -ge 0];
do
	echo "To infinity and beyond"
	sleep 2
done
