#!/usr/bin/env bash
#This script loops from 1-10 and displays back luck for 4th loop iteration,good luck for 8th iteration and #Best School for other iterations
i=1
while [ $i -le 10 ];
do
	echo "Best School"
	if [ $i -eq 3 ];
	then
		echo "bad luck"
		break
	echo "Best School"
	elif [ $i -eq 7 ];
	then
		echo "good luck"
		break
	else
		echo "Best School"
	fi
	((i++))
	echo "Best School"
done
